apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    cekit.io/version: 3.5.0
    commit.image.appsody.dev/author: Matthew P Wilson <matthew.wilson@uk.ibm.com>
    commit.image.appsody.dev/committer: GitHub Enterprise <noreply@github.ibm.com>
    commit.image.appsody.dev/date: Tue Feb 25 13:14:50 2020 +0000
    commit.image.appsody.dev/message: 'Merge pull request #2 from appsody-coffeeshop/update-deploy'
    graalvm-archive-filename: graalvm-ce-linux-amd64-19.2.1.tar.gz
    graalvm-archive-url: https://github.com/oracle/graal/releases/download/vm-19.2.1/graalvm-ce-linux-amd64-19.2.1.tar.gz
    image.opencontainers.org/created: "2020-03-25T10:32:15Z"
    image.opencontainers.org/documentation: https://github.ibm.com/appsody-coffeeshop/barista-kafka
    image.opencontainers.org/revision: 653dcfc0bfc06c0fbac57f0347adf9ca587f712c-modified
    image.opencontainers.org/source: https://github.ibm.com/appsody-coffeeshop/barista-kafka/tree/master
    image.opencontainers.org/url: https://github.ibm.com/appsody-coffeeshop/barista-kafka
    k8s.io/description: Quarkus.io builder image for building Quarkus applications.
    k8s.io/display-name: Centos + GraalVM + Maven Image
    maintainer: Quarkus Team <quarkus-dev@googlegroups.com>
    openshift.io/expose-services: 8080:http
    openshift.io/tags: builder,java,quarkus
    org/label-schema.build-date: "20190801"
    org/label-schema.license: GPLv2
    org/label-schema.name: CentOS Base Image
    org/label-schema.schema-version: "1.0"
    org/label-schema.vendor: CentOS
    stack.appsody.dev/authors: Paul Robinson <probinso@redhat.com>
    stack.appsody.dev/configured: docker.io/appsody/quarkus:0.2
    stack.appsody.dev/created: "2020-01-21T09:21:50Z"
    stack.appsody.dev/description: Quarkus runtime for running Java applications
    stack.appsody.dev/licenses: Apache-2.0
    stack.appsody.dev/tag: docker.io/appsody/quarkus:0.2.3
    stack.appsody.dev/title: Quarkus
  creationTimestamp: null
  labels:
    app.kubernetes.io/part-of: coffeeshop
    image.opencontainers.org/title: barista-kafka
    stack.appsody.dev/id: quarkus
    stack.appsody.dev/version: 0.2.3
  name: barista-kafka
spec:
  applicationImage: ianpartridge/barista-kafka:latest
  createKnativeService: false
  expose: true
  service:
    port: 8080
    type: ClusterIP
  stack: quarkus
  version: 1.0.0
