apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appsody-access-clusterrole
rules:
- apiGroups:
    - appsody.dev
  resources:
    - appsodyapplications
  verbs: 
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: appsody-access-clusterrolebinding
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: appsody-access-clusterrole
  subjects:
  - kind: ServiceAccount
    name: pipeline-service-account
    namespace: coffeeshop-pipelines