apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-using-kustomize
  namespace: coffeeshop-pipelines
spec:
  inputs:
    resources:
      - name: git-source
        type: git
    params:
      - name: pathToYaml
        description: Path to the kustomize yaml file within the git source
      - name: message
        default: "Default message"
  steps:
    - name: output-message
      image: bash
      command: ["bash", "-c"]
      args:
        - echo -e 'Trigger Message - $(inputs.params.message)'
    - name: run-kubectl-apply-k
      image: bitnami/kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-k"
        - "/workspace/git-source/$(inputs.params.pathToYaml)"
