apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  name: coffeeshop-ui
spec:
  env: 
    - name: COM_IBM_RUNTIMES_EVENTS_COFFEESHOP_HTTP_BARISTASERVICE_MP_REST_URL
      valueFrom:
        secretKeyRef:
          key: url
          name: coffeeshop-barista-http