apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-deploy
  namespace: coffeeshop-pipelines
spec:
  resources:
    - name: git-source
      type: git
  params:
    - name: message
      default: Local deployment pipeline has started
  tasks:
    - name: deploy-coffeeshop-demo
      taskRef:
        name: deploy-using-kustomize
      resources:
        inputs:
          - name: git-source
            resource: git-source
      params:
        - name: message
          value: $(params.message)
    - name: run-integration-tests
      taskRef:
        name: run-integration-tests
      params:
        - name: coffeeshop-host
          value: coffeeshop-ui-coffeeshop.apps.subject.os.fyre.ibm.com.bad
      runAfter:
        - deploy-coffeeshop-demo
