apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-deploy
  namespace: coffeeshop-pipelines
spec:
  resources:
    - name: git-source
      type: git
  params:
    - name: message
      default: Local deployment pipeline has started
    - name: branch
      description: The branch that started the pipeline
  tasks:
    - name: deploy-coffeeshop-demo
      taskRef:
        name: deploy-using-kustomize
      resources:
        inputs:
          - name: git-source
            resource: git-source
      params:
        - name: message
          value: $(params.message)
        - name: branch
          value: $(params.branch)
