apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-using-kustomize
  namespace: coffeeshop-pipelines
spec:
  inputs:
    resources:
      - name: git-source
        type: git
    params:
      - name: message
        description: The message that will be echoed.
      - name: branch
        description: The branch that started the pipeline
  steps:
    - name: output-message
      image: bash
      command: ["bash", "-c"]
      args:
        - echo -e 'Trigger Message - $(inputs.params.message)'
    - name: run-kubectl-apply-k
      image: bitnami/kubectl
      script: |
        #!/usr/bin/env sh
        name=`basename $(inputs.params.branch)`
        kubectl apply -k /workspace/git-source/env/$name
