apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: run-integration-tests
  namespace: coffeeshop-pipelines
spec:
  inputs:
    params:
      - name: coffeeshop-host
        description: Hostname for coffeeshop service
  steps:
    - name: run-tests
      securityContext:
        privileged: true
      image: matthewpwilson/coffeeshop-integration-tests:fri2
      env:
        - name: COFFEESHOP_HOST
          value: $(inputs.params.coffeeshop-host)
      script: |
        #!/usr/bin/env sh
        export COFFEESHOP_URI=http://$COFFEESHOP_HOST
        echo $COFFEESHOP_URI
        cd /project
        mvn clean verify




