apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: pipeline-binding
  namespace: coffeeshop-pipelines
spec:
  params:
  - name: gitrevision
    value: $(body.head_commit.id)
  - name: gitrepositoryurl
    value: $(body.repository.url)
  - name: contenttype
    value: $(header.Content-Type)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: prod-env
  namespace: coffeeshop-pipelines
spec:
  params:
  - name: environment
    value: prod