apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    cekit.io/version: 3.5.0
    commit.image.appsody.dev/author: Matthew P Wilson <matthew.wilson@uk.ibm.com>
    commit.image.appsody.dev/committer: GitHub Enterprise <noreply@github.ibm.com>
    commit.image.appsody.dev/contextDir: C:\Users\SandraHayward\Documents\Code\Appsody-Coffeeshop\barista-kafka
    commit.image.appsody.dev/date: Mon May 4 17:52:06 2020 +0100
    commit.image.appsody.dev/message: 'Merge pull request #6 from appsody-coffeeshop/auto-bind'
    graalvm-archive-filename: graalvm-ce-linux-amd64-19.2.1.tar.gz
    graalvm-archive-url: https://github.com/oracle/graal/releases/download/vm-19.2.1/graalvm-ce-linux-amd64-19.2.1.tar.gz
    image.opencontainers.org/created: "2020-06-09T10:32:28+01:00"
    image.opencontainers.org/documentation: https://github.ibm.com/appsody-coffeeshop/barista-kafka
    image.opencontainers.org/revision: 04191a081f9944e0908dce2f6da7a4106047d435
    image.opencontainers.org/source: |
      https://github.ibm.com/appsody-coffeeshop/barista-kafka/tree/master
    image.opencontainers.org/url: https://github.ibm.com/appsody-coffeeshop/barista-kafka
    k8s.io/description: Quarkus.io builder image for building Quarkus applications.
    k8s.io/display-name: Centos + GraalVM + Maven Image
    maintainer: Quarkus Team <quarkus-dev@googlegroups.com>
    openshift.io/expose-services: 8080:http
    openshift.io/tags: builder,java,quarkus
    org/label-schema.build-date: "20190801"
    org/label-schema.license: GPLv2
    org/label-schema.name: CentOS Base Image
    org/label-schema.schema-version: "1.0"
    org/label-schema.vendor: CentOS
    stack.appsody.dev/authors: Paul Robinson <probinso@redhat.com>
    stack.appsody.dev/configured: docker.io/appsody/quarkus:0.2
    stack.appsody.dev/created: "2020-01-21T09:21:50Z"
    stack.appsody.dev/description: Quarkus runtime for running Java applications
    stack.appsody.dev/licenses: Apache-2.0
    stack.appsody.dev/tag: docker.io/appsody/quarkus:0.2.3
    stack.appsody.dev/title: Quarkus
  creationTimestamp: null
  labels:
    app.kubernetes.io/part-of: coffeeshop
    image.opencontainers.org/title: barista-kafka
    monitor.appsody.dev/enabled: "true"
    stack.appsody.dev/id: quarkus
    stack.appsody.dev/version: 0.2.3
  name: barista-kafka
spec:
  applicationImage: ianpartridge/barista-kafka:latest
  pullPolicy: Always
  createKnativeService: false
  expose: true
  monitoring:
    labels:
      app.kubernetes.io/instance: barista-kafka
  service:
    annotations:
      prometheus.io/scrape: "true"
    port: 8082
    type: ClusterIP
  stack: quarkus
  version: 1.0.0
  envFrom:
    - secretRef:
        name: barista-kafka
